### ISSUE TITLE
Python version question

### ISSUE THREAD

**Issue by cheshire137** [pseudobeard/teambalancer#6]
I get this result when I try to run the script:

```
% python balance.py
Traceback (most recent call last):
  File "balance.py", line 3, in <module>
    import scraper
  File "/Users/cheshire137/code/cheshire137/teambalancer/scraper.py", line 3, in <module>
    import urllib.request
ImportError: No module named request
```

Is there a particular version of Python I should use? I'm on macOS.

```
% python --version
Python 2.7.11
```

**Comment by cheshire137** [comment]
Ooh I get no errors when I use my Homebrew-installed `python3` to run balance.py. I'll add a note to the readme!
